mode = "dark"

accent = "#e68e0d"
selection = "#2a1f12"
muted = "#5f4635"

background = "#0c0c0c"
dark_background = "#090909"
darker_background = "#060606"
lighter_background = "#33281d"

foreground = "#c9a36a"
dark_foreground = "#5f4635"
light_foreground = "#d8b880"
bright_foreground = "#f8e8c0"

red = "#7a4a28"
yellow = "#c99a4e"
orange = "#e68e0d"
green = "#c99a4e"
cyan = "#a08050"
blue = "#e68e0d"
magenta = "#8a5a3a"
brown = "#6b4630"

bright_red = "#9a5c35"
bright_yellow = "#e8b060"
bright_green = "#e8b060"
bright_cyan = "#d8b880"
bright_blue = "#f5a630"
bright_magenta = "#a07048"

hyprland_active_border = "#e68e0d #e68e0d 45deg"
